### PR TITLE
[WIP] Use Context API + some improvements

### PR DESCRIPTION
**Pull request by danielkcz**
I did a couple of changes, mostly to support an old & new way of doing things without breaking anything. Sadly I've managed to break some tests anyway. And some Typescript definitions are missing as well.

@johot Let me know if you want to have a look at it. Otherwise, I'll get to it probably later today or tomorrow.

### CODE REVIEW

**Comment by johot** [comment]
Looks good! I'll merge it! Would love for you to take a crack at the tests, I haven't worked in the mobx-react code base much before and only have limited experience with the new context api so go ahead! 

I'll merge this in and test with some real react projects.

**Comment by danielkcz** [comment]
Well, you were not supposed to merge it (there was a WIP in title) :) Oh well...

**Comment by johot** [comment]
Oops :P I will revert then hehe

**Comment by FredyC** [comment]
Well, so I've pushed some changes to master, but these tests are rather problematic and I cannot figure what's wrong there. What's for sure, it's caused by that new observer with hooks. Once I disable that, all tests are passing.

**Comment by danielkcz** [comment]
Well, so I've pushed some changes directly to master, mostly about deprecating Provider/inject, but avoiding any breaking changes. 

Tests are rather problematic and I cannot figure what's wrong there. I don't have much experience with rendering in tests just yet. What's for sure, it's caused by that new observer with hooks. Once I disable that, all tests are passing.

@mwestrate I think your help will be needed here.

**Comment by johot** [comment]
Nice work @FredyC ! I will test it as soon as I get back to work tomorrow (away for the weekend)!

**Pull request merged**
